/* =============================================
   js/education.js — Higher Education Data
   ============================================= */

const UNIVERSITIES = [
  /* ====== INDIAN ====== */
  {
    id:'iit-b', name:'IIT Bombay', location:'Mumbai, India', type:'Indian',
    ranking:'#1 India (QS 2024)', fees:'₹2.5L/year',
    programs:['M.Tech CS','M.Tech AI/ML','M.Tech Data Science','PhD Programs'],
    exams:['GATE','JAM','CEED'],
    placement:'₹25L avg CTC', scholarship:'Merit-cum-Means, SC/ST',
    domains:['AI','Data Science','Software','Research','Embedded'],
    url:'https://www.iitb.ac.in',
  },
  {
    id:'iit-d', name:'IIT Delhi', location:'New Delhi, India', type:'Indian',
    ranking:'#2 India (QS 2024)', fees:'₹2.5L/year',
    programs:['M.Tech CS','M.Tech AI','M.Tech ECE','PhD'],
    exams:['GATE','JAM'],
    placement:'₹24L avg CTC', scholarship:'Merit-cum-Means',
    domains:['AI','Software','Cybersecurity','Data Science','Research'],
    url:'https://home.iitd.ac.in',
  },
  {
    id:'iit-m', name:'IIT Madras', location:'Chennai, India', type:'Indian',
    ranking:'#3 India (QS 2024)', fees:'₹2.5L/year',
    programs:['M.Tech CS','M.Tech AI','M.Sc Data Science (Online)','PhD'],
    exams:['GATE','HSEE'],
    placement:'₹22L avg CTC', scholarship:'Merit-cum-Means, IITM Online',
    domains:['AI','Data Science','Research','Software'],
    url:'https://www.iitm.ac.in',
  },
  {
    id:'iit-kgp', name:'IIT Kharagpur', location:'West Bengal, India', type:'Indian',
    ranking:'#4 India (QS 2024)', fees:'₹2L/year',
    programs:['M.Tech CS','M.Tech AI','MBA','PhD'],
    exams:['GATE','JAM','CAT'],
    placement:'₹20L avg CTC', scholarship:'Merit-cum-Means',
    domains:['AI','Software','Embedded','Data Science'],
    url:'https://www.iitkgp.ac.in',
  },
  {
    id:'iim-a', name:'IIM Ahmedabad', location:'Ahmedabad, India', type:'Indian',
    ranking:'#1 Management India', fees:'₹35L total',
    programs:['MBA (PGP)','MBA (PGPX)','PhD'],
    exams:['CAT','GMAT'],
    placement:'₹32L avg CTC', scholarship:'Need-based',
    domains:['Business','Product','Analytics','Consulting'],
    url:'https://www.iima.ac.in',
  },
  {
    id:'iim-b', name:'IIM Bangalore', location:'Bangalore, India', type:'Indian',
    ranking:'#2 Management India', fees:'₹28L total',
    programs:['MBA (PGP)','M.Tech (Mgmt)','Executive MBA'],
    exams:['CAT','GMAT','GRE'],
    placement:'₹30L avg CTC', scholarship:'Need-based',
    domains:['Business','Product','Data Science','Consulting'],
    url:'https://www.iimb.ac.in',
  },
  {
    id:'bits', name:'BITS Pilani', location:'Rajasthan, India', type:'Indian',
    ranking:'Top 5 Private India', fees:'₹5L/year',
    programs:['M.Tech CS','M.Tech AI','M.Sc Mathematics','MBA'],
    exams:['BITSAT','GATE'],
    placement:'₹18L avg CTC', scholarship:'Merit Scholarships',
    domains:['AI','Software','Data Science','Research','Blockchain'],
    url:'https://www.bits-pilani.ac.in',
  },
  {
    id:'nit-t', name:'NIT Trichy', location:'Tamil Nadu, India', type:'Indian',
    ranking:'#1 NIT India', fees:'₹1.5L/year',
    programs:['M.Tech CS','M.Tech AI','M.Tech ECE'],
    exams:['GATE'],
    placement:'₹14L avg CTC', scholarship:'Merit-cum-Means',
    domains:['AI','Software','Embedded','Data Science'],
    url:'https://www.nitt.edu',
  },
  {
    id:'iisc', name:'IISc Bangalore', location:'Bangalore, India', type:'Indian',
    ranking:'#1 Research India', fees:'₹1.8L/year',
    programs:['M.Tech AI/ML','M.Sc Research','PhD','MTech (Research)'],
    exams:['GATE','JAM','KVPY'],
    placement:'₹28L avg CTC', scholarship:'Institute Fellowships',
    domains:['AI','Research','Data Science','Embedded','Software'],
    url:'https://www.iisc.ac.in',
  },
  {
    id:'iit-h', name:'IIT Hyderabad', location:'Hyderabad, India', type:'Indian',
    ranking:'Top 10 India', fees:'₹2L/year',
    programs:['M.Tech CS','M.Tech AI','M.Tech Data Science','PhD'],
    exams:['GATE'],
    placement:'₹19L avg CTC', scholarship:'Merit-cum-Means',
    domains:['AI','Software','Data Science','Research'],
    url:'https://iith.ac.in',
  },

  /* ====== FOREIGN ====== */
  {
    id:'mit', name:'MIT', location:'Cambridge, USA', type:'Foreign',
    ranking:'#1 World (QS 2024)', fees:'$60,000/year',
    programs:['MS CS','MS AI/ML','MEng','PhD'],
    exams:['GRE','TOEFL/IELTS'],
    placement:'$130K avg salary', scholarship:'Research Fellowships, RA/TA',
    domains:['AI','Research','Software','Data Science','Robotics'],
    url:'https://www.mit.edu',
  },
  {
    id:'stanford', name:'Stanford University', location:'California, USA', type:'Foreign',
    ranking:'#3 World (QS 2024)', fees:'$58,000/year',
    programs:['MS CS','MS AI','MS Data Science','MBA (GSB)','PhD'],
    exams:['GRE','GMAT','TOEFL'],
    placement:'$135K avg salary', scholarship:'University Fellowships, RA/TA',
    domains:['AI','Software','Data Science','Product','Blockchain','Research'],
    url:'https://www.stanford.edu',
  },
  {
    id:'cmu', name:'Carnegie Mellon University', location:'Pittsburgh, USA', type:'Foreign',
    ranking:'Top 5 CS World', fees:'$52,000/year',
    programs:['MS CS','MS ML','MS AI','MSIT','PhD'],
    exams:['GRE','TOEFL'],
    placement:'$130K avg salary', scholarship:'RA/TA, University Aid',
    domains:['AI','Software','Data Science','Cybersecurity','Research','NLP'],
    url:'https://www.cmu.edu',
  },
  {
    id:'caltech', name:'Caltech', location:'California, USA', type:'Foreign',
    ranking:'#6 World (QS 2024)', fees:'$60,000/year',
    programs:['MS CS','MS Applied Math','PhD'],
    exams:['GRE','TOEFL'],
    placement:'$125K avg salary', scholarship:'Research Fellowships',
    domains:['Research','AI','Data Science','Mathematics'],
    url:'https://www.caltech.edu',
  },
  {
    id:'cambridge', name:'University of Cambridge', location:'Cambridge, UK', type:'Foreign',
    ranking:'#2 World (QS 2024)', fees:'£35,000/year',
    placement:'£75K avg salary', scholarship:'Gates Cambridge, Chevening',
    programs:['MPhil CS','MPhil ML','PhD'],
    exams:['IELTS','GRE'],
    domains:['AI','Research','Data Science','Software'],
    url:'https://www.cam.ac.uk',
  },
  {
    id:'eth-zurich', name:'ETH Zurich', location:'Zurich, Switzerland', type:'Foreign',
    ranking:'#7 World (QS 2024)', fees:'CHF 730/year',
    programs:['MSc CS','MSc Data Science','MSc AI','PhD'],
    exams:['GRE (recommended)','IELTS/TOEFL'],
    placement:'€90K avg salary', scholarship:'Excellence Scholarship',
    domains:['AI','Research','Data Science','Software','Robotics'],
    url:'https://ethz.ch',
  },
  {
    id:'toronto', name:'University of Toronto', location:'Toronto, Canada', type:'Foreign',
    ranking:'#21 World (QS 2024)', fees:'CAD 30,000/year',
    programs:['MScAC','MASc CS','MEng AI','PhD'],
    exams:['GRE','IELTS/TOEFL'],
    placement:'CAD 95K avg salary', scholarship:'SGS Awards, RA/TA',
    domains:['AI','Software','Data Science','Research'],
    url:'https://www.utoronto.ca',
  },
  {
    id:'nus', name:'National University of Singapore', location:'Singapore', type:'Foreign',
    ranking:'#8 World (QS 2024)', fees:'SGD 22,000/year',
    programs:['MSc CS','MSc AI','MSc Data Science','MBA'],
    exams:['GRE','IELTS/TOEFL'],
    placement:'SGD 72K avg salary', scholarship:'Research Scholarships',
    domains:['AI','Software','Data Science','Business','Cybersecurity'],
    url:'https://www.nus.edu.sg',
  },
  {
    id:'oxford', name:'University of Oxford', location:'Oxford, UK', type:'Foreign',
    ranking:'#3 World (QS 2024)', fees:'£35,000/year',
    programs:['MSc CS','MSc Statistical Science','DPhil','MBA (Saïd)'],
    exams:['IELTS','GRE'],
    placement:'£80K avg salary', scholarship:'Rhodes, Clarendon',
    domains:['Research','AI','Data Science','Business','Software'],
    url:'https://www.ox.ac.uk',
  },
  {
    id:'waterloo', name:'University of Waterloo', location:'Ontario, Canada', type:'Foreign',
    ranking:'Top 15 CS World', fees:'CAD 18,000/year',
    programs:['MMath CS','MEng CS','MSc AI','PhD'],
    exams:['GRE','IELTS/TOEFL'],
    placement:'CAD 100K avg salary', scholarship:'Graduate Research Fellowships',
    domains:['AI','Software','Cybersecurity','Data Science','Research'],
    url:'https://uwaterloo.ca',
  },
];

/* ---------- Entrance Exams ---------- */
const ENTRANCE_EXAMS = [
  { id:'gate', name:'GATE', full:'Graduate Aptitude Test in Engineering', type:'Indian',
    forDomains:['AI','Software','Data Science','Embedded','Research'],
    eligibility:'B.Tech/B.E/B.Sc Engineering', month:'Feb', frequency:'Annual',
    desc:'Required for admission to M.Tech at IITs, NITs, IIITs and for PSU jobs.' },
  { id:'cat', name:'CAT', full:'Common Admission Test', type:'Indian',
    forDomains:['Business','Product','Analytics','Consulting'],
    eligibility:'Any graduate (≥50% marks)', month:'Nov', frequency:'Annual',
    desc:'Required for MBA at IIMs and 1000+ top B-schools in India.' },
  { id:'jam', name:'IIT JAM', full:'Joint Admission Test for MSc', type:'Indian',
    forDomains:['Research','Mathematics','Data Science'],
    eligibility:'B.Sc graduates', month:'Feb', frequency:'Annual',
    desc:'Admission to M.Sc, Joint M.Sc–PhD programs at IITs and IISc.' },
  { id:'gre', name:'GRE', full:'Graduate Record Examination', type:'Foreign',
    forDomains:['AI','Software','Data Science','Research','Cybersecurity'],
    eligibility:'Any graduate', month:'Year-round', frequency:'Up to 5/year',
    desc:'Required for MS/PhD admission at most US, European & Australian universities.' },
  { id:'gmat', name:'GMAT', full:'Graduate Management Admission Test', type:'Foreign',
    forDomains:['Business','Product','Consulting','Analytics'],
    eligibility:'Any graduate', month:'Year-round', frequency:'Up to 5/year',
    desc:'Required for MBA at top global business schools.' },
  { id:'ielts', name:'IELTS', full:'International English Language Testing System', type:'Foreign',
    forDomains:['AI','Software','Data Science','Business','Research'],
    eligibility:'Anyone', month:'Year-round', frequency:'Unlimited',
    desc:'English proficiency test required by most UK, Australian, Canadian universities.' },
  { id:'toefl', name:'TOEFL', full:'Test of English as a Foreign Language', type:'Foreign',
    forDomains:['AI','Software','Data Science','Business','Research'],
    eligibility:'Anyone', month:'Year-round', frequency:'Unlimited',
    desc:'English proficiency test required by US and some European universities.' },
];

/* ---------- Scholarships ---------- */
const SCHOLARSHIPS = [
  { name:'Gates Cambridge Scholarship', country:'UK', amount:'Full funding + £18K stipend', provider:'Gates Foundation', domains:['All'] },
  { name:'Chevening Scholarship', country:'UK', amount:'Full funding', provider:'UK Government', domains:['All'] },
  { name:'Inlaks Scholarship', country:'India/Abroad', amount:'Up to $100K', provider:'Inlaks Foundation', domains:['All'] },
  { name:'Tata Trust Scholarships', country:'USA', amount:'Up to $25K', provider:'Tata Trusts', domains:['All'] },
  { name:'DAAD Scholarship', country:'Germany', amount:'Full funding', provider:'German Govt', domains:['Research','Engineering'] },
  { name:'Erasmus+ Scholarship', country:'Europe', amount:'€1,000/month', provider:'EU', domains:['All'] },
  { name:'Commonwealth Scholarship', country:'UK', amount:'Full funding', provider:'UK Govt', domains:['All'] },
  { name:'IITM Online Scholarship', country:'India', amount:'Fee waiver', provider:'IIT Madras', domains:['Data Science','AI'] },
];

/* ---------- Filter logic ---------- */
function getUniversitiesForCareer(careerDomain) {
  return UNIVERSITIES.filter(u => u.domains.some(d => d.toLowerCase().includes(careerDomain.toLowerCase())));
}

function getExamsForDomain(domain) {
  return ENTRANCE_EXAMS.filter(e => e.forDomains.some(d => d.toLowerCase().includes(domain.toLowerCase())));
}
