"""
sample_occupations.py
======================
A hand-curated set of ~80 occupations spanning every major O*NET job
family, used so career_ai_engine.py is fully runnable offline/without
network access. Each occupation has real O*NET-style skill importance
ratings (0-5) and RIASEC (Holland Code) interest scores (0-7).

This is a SAMPLE, not the full dataset. For the real ~900-occupation O*NET
database (essentially the entire US occupational taxonomy), use
ONetDataLoader.load_from_onet_files() or download_and_load() in
career_ai_engine.py — those give you the complete, official dataset instead
of this illustrative subset.
"""
try:
    from .career_ai_engine import Occupation
except ImportError:  # pragma: no cover - fallback for direct script execution
    from career_ai_engine import Occupation

# Each entry: (title, description, {skill: importance 0-5, ...}, {riasec: 0-7, ...}, job_zone)
_RAW = [
    ("Software Developer", "Design, build, and maintain software applications and systems.",
     {"Programming": 5, "Complex Problem Solving": 4.5, "Systems Analysis": 4, "Critical Thinking": 4, "Troubleshooting": 4},
     {"Investigative": 6, "Realistic": 4, "Conventional": 3}, 4),
    ("Data Scientist", "Analyze large datasets to extract insights and build predictive models.",
     {"Mathematics": 5, "Science": 4, "Programming": 4.5, "Critical Thinking": 4.5, "Complex Problem Solving": 4.5},
     {"Investigative": 7, "Conventional": 4}, 5),
    ("Machine Learning Engineer", "Build and deploy AI/ML systems and production model pipelines.",
     {"Programming": 5, "Mathematics": 4.5, "Systems Analysis": 4, "Complex Problem Solving": 4.5, "Troubleshooting": 4},
     {"Investigative": 6.5, "Realistic": 3.5}, 5),
    ("Cybersecurity Analyst", "Protect computer systems and networks from security threats.",
     {"Troubleshooting": 4.5, "Systems Analysis": 4.5, "Critical Thinking": 4.5, "Judgment and Decision Making": 4, "Programming": 3.5},
     {"Investigative": 5.5, "Conventional": 4.5, "Realistic": 3}, 4),
    ("Network Administrator", "Maintain computer networks and troubleshoot connectivity issues.",
     {"Troubleshooting": 4.5, "Installation": 4, "Equipment Maintenance": 3.5, "Systems Analysis": 4, "Operations Monitoring": 4},
     {"Realistic": 5, "Investigative": 4, "Conventional": 3.5}, 3),
    ("UX/UI Designer", "Design intuitive, visually engaging digital product experiences.",
     {"Technology Design": 4.5, "Critical Thinking": 4, "Social Perceptiveness": 4, "Writing": 3, "Coordination": 3.5},
     {"Artistic": 6, "Investigative": 4, "Social": 3.5}, 4),
    ("Civil Engineer", "Design and oversee construction of infrastructure like roads and bridges.",
     {"Mathematics": 4.5, "Science": 4, "Technology Design": 4.5, "Systems Analysis": 4, "Judgment and Decision Making": 4},
     {"Realistic": 5.5, "Investigative": 5, "Conventional": 3.5}, 4),
    ("Mechanical Engineer", "Design, develop, and test mechanical devices and systems.",
     {"Mathematics": 4.5, "Science": 4.5, "Technology Design": 4.5, "Complex Problem Solving": 4, "Troubleshooting": 3.5},
     {"Realistic": 5.5, "Investigative": 5.5}, 4),
    ("Electrical Engineer", "Design and develop electrical systems, equipment, and components.",
     {"Mathematics": 4.5, "Science": 4.5, "Technology Design": 4.5, "Troubleshooting": 4, "Systems Evaluation": 4},
     {"Realistic": 5, "Investigative": 5.5}, 4),
    ("Aerospace Engineer", "Design aircraft, spacecraft, and related systems and components.",
     {"Mathematics": 5, "Science": 5, "Technology Design": 4.5, "Systems Analysis": 4.5, "Complex Problem Solving": 4.5},
     {"Investigative": 6, "Realistic": 5}, 5),
    ("Robotics Engineer", "Design, build, and program robotic systems for industry and research.",
     {"Programming": 4.5, "Technology Design": 4.5, "Mathematics": 4, "Troubleshooting": 4, "Systems Analysis": 4},
     {"Realistic": 5.5, "Investigative": 5.5}, 5),
    ("Physician (General Practice)", "Diagnose and treat illnesses, injuries, and provide preventive care.",
     {"Science": 5, "Critical Thinking": 4.5, "Judgment and Decision Making": 4.5, "Social Perceptiveness": 4, "Active Listening": 4.5},
     {"Investigative": 6, "Social": 5.5}, 5),
    ("Registered Nurse", "Provide and coordinate patient care, educate patients about health conditions.",
     {"Active Listening": 4.5, "Service Orientation": 4.5, "Social Perceptiveness": 4.5, "Critical Thinking": 4, "Monitoring": 4},
     {"Social": 6, "Investigative": 3.5, "Realistic": 3}, 4),
    ("Physical Therapist", "Help injured or ill patients improve movement and manage pain.",
     {"Science": 4, "Active Listening": 4.5, "Service Orientation": 4.5, "Instructing": 4, "Social Perceptiveness": 4},
     {"Social": 6, "Realistic": 4, "Investigative": 3.5}, 5),
    ("Dentist", "Diagnose and treat problems with teeth, gums, and mouth.",
     {"Science": 4.5, "Critical Thinking": 4, "Operation and Control": 4, "Judgment and Decision Making": 4.5, "Service Orientation": 4},
     {"Realistic": 4.5, "Investigative": 5, "Social": 4}, 5),
    ("Pharmacist", "Dispense medications and advise on safe drug usage.",
     {"Science": 4.5, "Mathematics": 3.5, "Critical Thinking": 4, "Service Orientation": 4, "Quality Control Analysis": 4},
     {"Investigative": 5.5, "Conventional": 4.5, "Social": 3.5}, 5),
    ("Veterinarian", "Diagnose and treat diseases and injuries in animals.",
     {"Science": 4.5, "Critical Thinking": 4.5, "Judgment and Decision Making": 4.5, "Service Orientation": 4, "Active Listening": 4},
     {"Investigative": 5.5, "Realistic": 4.5, "Social": 4}, 5),
    ("Psychologist", "Study mental processes and behavior, help clients manage issues.",
     {"Active Listening": 5, "Social Perceptiveness": 5, "Critical Thinking": 4, "Judgment and Decision Making": 4, "Service Orientation": 4},
     {"Social": 6.5, "Investigative": 5.5}, 5),
    ("Occupational Therapist", "Help patients develop, recover, and improve daily living skills.",
     {"Active Listening": 4.5, "Service Orientation": 4.5, "Social Perceptiveness": 4, "Instructing": 4, "Critical Thinking": 3.5},
     {"Social": 6, "Realistic": 3.5, "Investigative": 3.5}, 5),
    ("Medical Laboratory Technician", "Perform tests on samples to help diagnose disease.",
     {"Science": 4.5, "Quality Control Analysis": 4.5, "Critical Thinking": 3.5, "Monitoring": 4, "Operation and Control": 3.5},
     {"Investigative": 5, "Realistic": 4, "Conventional": 3.5}, 3),
    ("Teacher (Secondary School)", "Educate students in a specific subject area at the high school level.",
     {"Instructing": 5, "Speaking": 4.5, "Active Listening": 4, "Learning Strategies": 4.5, "Social Perceptiveness": 4},
     {"Social": 6, "Artistic": 3.5, "Investigative": 3.5}, 4),
    ("Elementary School Teacher", "Teach fundamental academic and social skills to young children.",
     {"Instructing": 5, "Speaking": 4.5, "Active Listening": 4.5, "Learning Strategies": 4, "Social Perceptiveness": 4.5},
     {"Social": 6.5, "Artistic": 3}, 4),
    ("University Professor", "Teach and conduct original research in a specialized academic field.",
     {"Instructing": 4.5, "Writing": 4.5, "Science": 4, "Critical Thinking": 4.5, "Active Learning": 4.5},
     {"Investigative": 6, "Social": 4.5, "Artistic": 3}, 5),
    ("School Counselor", "Help students develop academic, career, and personal skills.",
     {"Active Listening": 5, "Social Perceptiveness": 4.5, "Service Orientation": 4.5, "Instructing": 3.5, "Speaking": 4},
     {"Social": 6.5, "Conventional": 3}, 4),
    ("Librarian", "Help people find information and manage library collections.",
     {"Reading Comprehension": 4.5, "Active Listening": 4, "Service Orientation": 4, "Critical Thinking": 3.5, "Time Management": 3.5},
     {"Conventional": 4.5, "Social": 4.5, "Investigative": 3.5}, 4),
    ("Graphic Designer", "Create visual concepts to communicate ideas for print and digital media.",
     {"Technology Design": 4, "Writing": 3, "Critical Thinking": 3.5, "Time Management": 3.5, "Coordination": 3},
     {"Artistic": 6.5, "Realistic": 3}, 3),
    ("Film/Video Editor", "Edit raw footage into a polished, finished film or video product.",
     {"Technology Design": 3.5, "Critical Thinking": 3.5, "Time Management": 4, "Coordination": 3.5, "Quality Control Analysis": 3.5},
     {"Artistic": 6, "Realistic": 3.5}, 3),
    ("Musician / Composer", "Perform, write, or arrange music for audiences or recordings.",
     {"Active Learning": 3.5, "Coordination": 3.5, "Time Management": 3, "Monitoring": 3},
     {"Artistic": 7, "Realistic": 2.5}, 3),
    ("Photographer", "Capture and edit images for artistic, journalistic, or commercial purposes.",
     {"Technology Design": 3.5, "Critical Thinking": 3, "Time Management": 3.5, "Service Orientation": 3},
     {"Artistic": 6.5, "Realistic": 3.5}, 2),
    ("Journalist / Reporter", "Research, write, and report news stories for print, broadcast, or online media.",
     {"Writing": 5, "Reading Comprehension": 4.5, "Active Listening": 4, "Critical Thinking": 4, "Speaking": 4},
     {"Artistic": 5, "Investigative": 4.5, "Enterprising": 3.5}, 4),
    ("Novelist / Author", "Write original long-form fiction or non-fiction work.",
     {"Writing": 5, "Reading Comprehension": 4, "Active Learning": 3.5, "Time Management": 3.5},
     {"Artistic": 7, "Investigative": 4}, 3),
    ("Interior Designer", "Plan and design functional, safe, and aesthetic interior spaces.",
     {"Technology Design": 4, "Coordination": 3.5, "Critical Thinking": 3.5, "Service Orientation": 3.5, "Time Management": 3.5},
     {"Artistic": 6, "Realistic": 3.5, "Enterprising": 3}, 3),
    ("Architect", "Design buildings and oversee their construction.",
     {"Technology Design": 4.5, "Mathematics": 4, "Critical Thinking": 4, "Coordination": 4, "Systems Evaluation": 3.5},
     {"Artistic": 5, "Investigative": 4.5, "Realistic": 4.5}, 5),
    ("Fashion Designer", "Create clothing and accessory designs, from concept to production.",
     {"Technology Design": 4, "Time Management": 3.5, "Coordination": 3.5, "Critical Thinking": 3},
     {"Artistic": 6.5, "Enterprising": 3.5}, 3),
    ("Actor", "Perform roles in theater, film, or television productions.",
     {"Speaking": 4, "Active Learning": 3.5, "Coordination": 3, "Social Perceptiveness": 3.5},
     {"Artistic": 7, "Social": 4}, 2),
    ("Accountant", "Prepare and examine financial records, ensure accuracy and compliance.",
     {"Mathematics": 4.5, "Critical Thinking": 4, "Reading Comprehension": 4, "Time Management": 4, "Quality Control Analysis": 4},
     {"Conventional": 6.5, "Enterprising": 3}, 4),
    ("Financial Analyst", "Evaluate investment opportunities and financial performance.",
     {"Mathematics": 4.5, "Critical Thinking": 4.5, "Judgment and Decision Making": 4, "Management of Financial Resources": 4, "Writing": 3.5},
     {"Investigative": 5, "Conventional": 5, "Enterprising": 4}, 4),
    ("Marketing Manager", "Plan and oversee marketing strategies and campaigns.",
     {"Persuasion": 4.5, "Speaking": 4, "Management of Personnel Resources": 4, "Judgment and Decision Making": 4, "Writing": 3.5},
     {"Enterprising": 6, "Artistic": 4}, 4),
    ("Sales Manager", "Lead a sales team and set targets to drive revenue growth.",
     {"Persuasion": 5, "Negotiation": 4.5, "Management of Personnel Resources": 4.5, "Speaking": 4.5, "Coordination": 4},
     {"Enterprising": 6.5, "Social": 4}, 4),
    ("Human Resources Manager", "Oversee recruitment, employee relations, and workplace policy.",
     {"Social Perceptiveness": 4.5, "Management of Personnel Resources": 4.5, "Negotiation": 4, "Active Listening": 4.5, "Judgment and Decision Making": 4},
     {"Social": 5.5, "Enterprising": 4.5, "Conventional": 3.5}, 4),
    ("Management Consultant", "Advise organizations on improving performance and solving business problems.",
     {"Critical Thinking": 4.5, "Complex Problem Solving": 4.5, "Persuasion": 4, "Systems Analysis": 4, "Writing": 4},
     {"Enterprising": 5.5, "Investigative": 5}, 4),
    ("Entrepreneur / Startup Founder", "Launch and grow a new business venture from the ground up.",
     {"Judgment and Decision Making": 4.5, "Persuasion": 4.5, "Management of Financial Resources": 4, "Complex Problem Solving": 4.5, "Negotiation": 4},
     {"Enterprising": 7, "Artistic": 3.5, "Investigative": 3.5}, 4),
    ("Investment Banker", "Raise capital, advise on mergers/acquisitions, and manage large financial deals.",
     {"Mathematics": 4.5, "Negotiation": 4.5, "Judgment and Decision Making": 4.5, "Persuasion": 4, "Time Management": 4.5},
     {"Enterprising": 6, "Conventional": 4.5}, 5),
    ("Actuary", "Analyze financial risk using mathematics, statistics, and financial theory.",
     {"Mathematics": 5, "Critical Thinking": 4.5, "Complex Problem Solving": 4, "Judgment and Decision Making": 4},
     {"Investigative": 5.5, "Conventional": 5.5}, 5),
    ("Economist", "Study production and distribution of resources, goods, and services.",
     {"Mathematics": 4.5, "Science": 3.5, "Critical Thinking": 4.5, "Writing": 4, "Complex Problem Solving": 4},
     {"Investigative": 6, "Conventional": 4}, 5),
    ("Supply Chain / Logistics Manager", "Coordinate the movement of goods from suppliers to customers.",
     {"Management of Material Resources": 4.5, "Coordination": 4.5, "Systems Analysis": 4, "Judgment and Decision Making": 4, "Time Management": 4.5},
     {"Conventional": 5, "Enterprising": 4.5, "Realistic": 3.5}, 4),
    ("Electrician", "Install, maintain, and repair electrical wiring and systems.",
     {"Troubleshooting": 4.5, "Repairing": 4.5, "Installation": 4.5, "Equipment Maintenance": 4, "Quality Control Analysis": 3.5},
     {"Realistic": 6.5, "Conventional": 3}, 3),
    ("Plumber", "Install and repair pipes and fixtures for water, gas, and drainage systems.",
     {"Troubleshooting": 4, "Repairing": 4.5, "Installation": 4.5, "Equipment Maintenance": 4},
     {"Realistic": 6.5}, 3),
    ("HVAC Technician", "Install and service heating, ventilation, and air conditioning systems.",
     {"Troubleshooting": 4.5, "Repairing": 4.5, "Equipment Maintenance": 4.5, "Installation": 4},
     {"Realistic": 6.5, "Conventional": 3}, 3),
    ("Automotive Mechanic", "Diagnose, repair, and maintain vehicles.",
     {"Troubleshooting": 4.5, "Repairing": 4.5, "Equipment Maintenance": 4, "Quality Control Analysis": 3.5},
     {"Realistic": 6.5}, 3),
    ("Carpenter", "Construct, install, and repair building frameworks and structures made of wood.",
     {"Installation": 4, "Repairing": 3.5, "Mathematics": 3, "Equipment Maintenance": 3},
     {"Realistic": 6.5, "Artistic": 3}, 3),
    ("Welder", "Join metal parts using heat and specialized equipment.",
     {"Operation and Control": 4.5, "Quality Control Analysis": 4, "Equipment Maintenance": 3.5, "Troubleshooting": 3.5},
     {"Realistic": 6.5}, 2),
    ("Construction Manager", "Plan, coordinate, and supervise construction projects.",
     {"Management of Material Resources": 4.5, "Coordination": 4.5, "Judgment and Decision Making": 4, "Time Management": 4.5, "Management of Personnel Resources": 4},
     {"Realistic": 5, "Enterprising": 5, "Conventional": 3.5}, 4),
    ("Pilot (Commercial Airline)", "Fly and navigate aircraft to transport passengers or cargo.",
     {"Operation and Control": 4.5, "Monitoring": 4.5, "Judgment and Decision Making": 4.5, "Coordination": 4, "Systems Evaluation": 4},
     {"Realistic": 5.5, "Investigative": 4}, 4),
    ("Commercial Truck Driver", "Transport goods over long distances via truck.",
     {"Operation and Control": 4, "Monitoring": 3.5, "Time Management": 3.5},
     {"Realistic": 6}, 2),
    ("Air Traffic Controller", "Direct aircraft movements to ensure safe and efficient air traffic flow.",
     {"Monitoring": 5, "Coordination": 4.5, "Judgment and Decision Making": 4.5, "Operations Monitoring": 4.5},
     {"Conventional": 5, "Realistic": 4, "Investigative": 4}, 4),
    ("Chef / Head Cook", "Plan menus and prepare food in a professional kitchen.",
     {"Management of Material Resources": 3.5, "Time Management": 4, "Coordination": 4, "Management of Personnel Resources": 3.5},
     {"Artistic": 5, "Realistic": 5}, 3),
    ("Hotel Manager", "Oversee daily operations of a hotel or lodging establishment.",
     {"Management of Personnel Resources": 4.5, "Service Orientation": 4.5, "Coordination": 4.5, "Management of Financial Resources": 4},
     {"Enterprising": 5, "Social": 4.5, "Conventional": 3.5}, 4),
    ("Event Planner", "Coordinate all aspects of professional or personal events.",
     {"Coordination": 4.5, "Time Management": 4.5, "Negotiation": 4, "Service Orientation": 4},
     {"Enterprising": 5, "Artistic": 4, "Social": 4}, 3),
    ("Flight Attendant", "Ensure safety and comfort of airline passengers.",
     {"Service Orientation": 4.5, "Active Listening": 4, "Social Perceptiveness": 4, "Coordination": 3.5},
     {"Social": 5.5, "Enterprising": 3.5}, 2),
    ("Social Worker", "Help individuals and families cope with challenges and access resources.",
     {"Active Listening": 4.5, "Social Perceptiveness": 5, "Service Orientation": 4.5, "Negotiation": 3.5, "Judgment and Decision Making": 4},
     {"Social": 6.5, "Investigative": 3.5}, 4),
    ("Police Officer", "Protect life and property and enforce laws.",
     {"Judgment and Decision Making": 4.5, "Social Perceptiveness": 4, "Active Listening": 4, "Coordination": 4},
     {"Realistic": 5, "Social": 4, "Enterprising": 3.5}, 3),
    ("Firefighter", "Respond to fires and emergencies to protect life and property.",
     {"Judgment and Decision Making": 4.5, "Coordination": 4.5, "Equipment Maintenance": 3.5, "Operation and Control": 4},
     {"Realistic": 6.5, "Social": 4}, 3),
    ("Paramedic / EMT", "Provide emergency medical care and transport patients.",
     {"Judgment and Decision Making": 4.5, "Active Listening": 4, "Science": 3.5, "Coordination": 4},
     {"Social": 5, "Realistic": 5, "Investigative": 3.5}, 3),
    ("Lawyer", "Advise and represent clients on legal matters.",
     {"Reading Comprehension": 5, "Writing": 4.5, "Critical Thinking": 4.5, "Negotiation": 4.5, "Persuasion": 4.5},
     {"Enterprising": 5.5, "Investigative": 5}, 5),
    ("Paralegal", "Support lawyers by researching and preparing legal documents.",
     {"Reading Comprehension": 4.5, "Writing": 4, "Critical Thinking": 3.5, "Time Management": 4},
     {"Conventional": 5, "Investigative": 4}, 3),
    ("Judge", "Preside over legal proceedings and make rulings in court.",
     {"Judgment and Decision Making": 5, "Reading Comprehension": 4.5, "Critical Thinking": 4.5, "Active Listening": 4},
     {"Conventional": 4.5, "Enterprising": 4, "Investigative": 4}, 5),
    ("Urban Planner", "Develop land use plans for communities and regions.",
     {"Systems Analysis": 4, "Critical Thinking": 4, "Writing": 3.5, "Coordination": 3.5, "Judgment and Decision Making": 4},
     {"Investigative": 5, "Artistic": 3.5, "Conventional": 3.5}, 5),
    ("Environmental Scientist", "Study environmental problems and develop solutions.",
     {"Science": 5, "Critical Thinking": 4.5, "Complex Problem Solving": 4, "Writing": 3.5, "Systems Analysis": 3.5},
     {"Investigative": 6, "Realistic": 4}, 4),
    ("Geologist", "Study the physical structure of the earth and its history.",
     {"Science": 5, "Critical Thinking": 4, "Complex Problem Solving": 4, "Mathematics": 3.5},
     {"Investigative": 6, "Realistic": 4.5}, 5),
    ("Marine Biologist", "Study organisms and ecosystems in oceans and other bodies of water.",
     {"Science": 5, "Critical Thinking": 4, "Active Learning": 4, "Writing": 3.5},
     {"Investigative": 6.5, "Realistic": 4.5}, 5),
    ("Astronomer", "Study celestial objects and phenomena using observation and theory.",
     {"Mathematics": 5, "Science": 5, "Critical Thinking": 4.5, "Complex Problem Solving": 4.5},
     {"Investigative": 7}, 5),
    ("Chemist", "Study substances and their properties, conduct experiments.",
     {"Science": 5, "Mathematics": 4, "Quality Control Analysis": 4, "Critical Thinking": 4.5},
     {"Investigative": 6.5, "Realistic": 3.5}, 5),
    ("Biomedical Researcher", "Conduct research to advance understanding of biology and medicine.",
     {"Science": 5, "Critical Thinking": 4.5, "Active Learning": 4.5, "Writing": 4, "Complex Problem Solving": 4.5},
     {"Investigative": 7}, 5),
    ("Farmer / Agricultural Manager", "Manage crop production and/or livestock on a farm.",
     {"Management of Material Resources": 4, "Judgment and Decision Making": 4, "Equipment Maintenance": 3.5, "Monitoring": 4},
     {"Realistic": 6, "Enterprising": 4, "Conventional": 3}, 3),
    ("Agricultural Engineer", "Design equipment, structures, and processes for agriculture.",
     {"Technology Design": 4, "Science": 4, "Mathematics": 4, "Complex Problem Solving": 4},
     {"Realistic": 5, "Investigative": 5}, 4),
    ("Forester", "Manage and protect forest resources and plan sustainable harvesting.",
     {"Science": 4, "Management of Material Resources": 3.5, "Judgment and Decision Making": 4, "Monitoring": 4},
     {"Realistic": 5.5, "Investigative": 4.5}, 4),
    ("Athletic Coach", "Train and guide athletes to improve performance and achieve goals.",
     {"Instructing": 4.5, "Coordination": 4, "Social Perceptiveness": 4, "Judgment and Decision Making": 4, "Active Listening": 3.5},
     {"Social": 5.5, "Realistic": 4.5, "Enterprising": 3.5}, 3),
    ("Professional Athlete", "Compete at an elite level in an organized sport.",
     {"Coordination": 5, "Time Management": 3.5, "Monitoring": 3.5},
     {"Realistic": 6.5, "Enterprising": 3.5}, 2),
    ("Personal Trainer", "Design and guide individualized fitness programs for clients.",
     {"Instructing": 4.5, "Service Orientation": 4.5, "Active Listening": 4, "Coordination": 3.5},
     {"Social": 5.5, "Realistic": 5, "Enterprising": 3.5}, 2),
    ("Video Game Designer", "Design gameplay mechanics, levels, and systems for video games.",
     {"Technology Design": 4, "Programming": 3.5, "Critical Thinking": 4, "Coordination": 3.5, "Writing": 3},
     {"Artistic": 6, "Investigative": 4.5, "Realistic": 3}, 4),
    ("Animator", "Create moving images and characters using digital or traditional techniques.",
     {"Technology Design": 4, "Time Management": 3.5, "Critical Thinking": 3, "Coordination": 3},
     {"Artistic": 6.5, "Realistic": 3}, 3),
    ("Air Force / Military Officer", "Lead and coordinate military personnel and operations.",
     {"Management of Personnel Resources": 4.5, "Judgment and Decision Making": 4.5, "Coordination": 4.5, "Operations Monitoring": 4},
     {"Realistic": 5, "Enterprising": 5, "Conventional": 3.5}, 4),
    ("Real Estate Agent", "Help clients buy, sell, and rent properties.",
     {"Persuasion": 4.5, "Negotiation": 4.5, "Service Orientation": 4, "Speaking": 4},
     {"Enterprising": 6, "Social": 4}, 3),
    ("Insurance Underwriter", "Evaluate insurance applications and determine coverage terms.",
     {"Mathematics": 4, "Judgment and Decision Making": 4.5, "Critical Thinking": 4, "Quality Control Analysis": 4},
     {"Conventional": 6, "Investigative": 3.5}, 3),
    ("Translator / Interpreter", "Convert spoken or written language from one language to another.",
     {"Active Listening": 4.5, "Reading Comprehension": 4.5, "Speaking": 4.5, "Writing": 4},
     {"Artistic": 4, "Social": 4.5, "Conventional": 3.5}, 3),
    ("Data Engineer", "Build and maintain the infrastructure and pipelines for large-scale data systems.",
     {"Programming": 5, "Systems Analysis": 4.5, "Troubleshooting": 4, "Complex Problem Solving": 4},
     {"Investigative": 5.5, "Conventional": 4}, 4),
    ("Product Manager", "Define product vision and coordinate teams to build and ship it.",
     {"Judgment and Decision Making": 4.5, "Coordination": 4.5, "Persuasion": 4, "Systems Analysis": 3.5, "Writing": 3.5},
     {"Enterprising": 5.5, "Investigative": 4, "Artistic": 3}, 4),
]


def _build() -> list:
    occs = []
    for i, (title, desc, skills, riasec, zone) in enumerate(_RAW):
        occs.append(Occupation(
            soc_code=f"SAMPLE-{i:03d}",
            title=title,
            description=desc,
            skills=skills,
            riasec=riasec,
            job_zone=zone,
        ))
    return occs


SAMPLE_OCCUPATIONS = _build()
